More locking.  Timing has been adjusted to give every process a reasonable chance to run.

diff --git a/files/bin/flexget_execute_now b/files/bin/flexget_execute_now
--- a/files/bin/flexget_execute_now
+++ b/files/bin/flexget_execute_now
@@ -1,15 +1,34 @@
 #!/bin/bash
 
-# DISTRIBUTED BY ANSIBLE
+export lock_file='/tmp/update_debian.lock'
+export log_tag="${0##*/} (${$})"
+export log="logger -t '${log_tag}'"
 
 # Just skip it unless transmission is running.
 if /usr/sbin/service transmission-daemon status >/dev/null 2>&1; then
-  date --iso-8601=seconds > /var/log/flexget_execute.log 2>&1
-  # Don't use --cron.  It suppresses all the output I want to log.
-  /usr/local/bin/flexget execute >> /var/log/flexget_execute.log 2>&1
-  echo ${?} > /var/log/flexget_execute.ret
-  date --iso-8601=seconds >> /var/log/flexget_execute.log 2>&1
-else
-  echo 'Error:  Transmission is not running.' > /var/log/flexget_execute.log
-  echo 1 > /var/log/flexget_execute.ret
+  $log "Acquiring lock."
+  if ! flock -n "${lock_file}" -c '
+    echo $$ > "${lock_file}"
+    ps -lfp $$ >> "${lock_file}"
+    date --iso-8601=seconds > /var/log/flexget_execute.log 2>&1
+    # Don not use --cron.  It suppresses all the output I want to log.
+    /usr/local/bin/flexget execute >> /var/log/flexget_execute.log 2>&1
+    echo "${?}" > /var/log/flexget_execute.ret
+    date --iso-8601=seconds >> /var/log/flexget_execute.log 2>&1
+  else
+    echo "Error:  Transmission is not running." > /var/log/flexget_execute.log
+    echo 1 > /var/log/flexget_execute.ret
+'; then
+  ret="${?}"
+  $log "Lock held by PID:  $(
+    head -n 1 "${lock_file}"
+  )"
+  $log "$(
+    tail -n 1 "${lock_file}"
+  )"
 fi
+
+$log "Lock released.  flock return status:  ${?}"
+
+# Removing the lock file, before or after unlocking, breaks flock's
+# expectations.  Just leave it.
